bind 127.0.0.1:5354
ca-file /etc/ssl/certs/ca-certificates.crt
cache-size 500000
cache-persist yes
cache-file /var/cache/smartdns.cache
prefetch-domain yes
serve-expired yes
serve-expired-ttl 86400
speed-check-mode tcp:443,tcp:80
force-AAAA-SOA yes

# Local PowerDNS Recursor (untuk DNS internal)
server 127.0.0.1:5353

# Cloudflare DoH
#server-https https://1.1.1.1/dns-query -host-name cloudflare-dns.com
#server-https https://1.0.0.1/dns-query -host-name cloudflare-dns.com
server-tls 1.1.1.1:853 -host-name cloudflare-dns.com
server-tls 1.0.0.1:853 -host-name cloudflare-dns.com

#server-https https://cloudflare-dns.com/dns-query -bootstrap-ip 1.1.1.1
#server-https https://cloudflare-dns.com/dns-query -bootstrap-ip 1.0.0.1

# Quad9 DoT (tercepat di setup kamu, 12ms)
server-tls 9.9.9.9:853


# OpenDNS — opsional, paling lambat (24ms), comment kalau tidak butuh
server-tls 208.67.222.222:853

log-level info
log-file /var/log/smartdns.log
log-size 10m
log-num 2

conf-file /etc/smartdns/safesearch.conf

plugin /usr/local/lib/smartdns/smartdns_ui.so
smartdns-ui.www-root /usr/share/smartdns/wwwroot
smartdns-ui.ip http://[::]:6080
smartdns-ui.enable-terminal yes
smartdns-ui.max-query-log-age 86400
