# SafeSearch Google
cname /www.google.com/forcesafesearch.google.com
cname /www.google.co.id/forcesafesearch.google.com
# YouTube Restrict
#cname /www.youtube.com/restrict.youtube.com
#cname /m.youtube.com/restrict.youtube.com
#cname /youtubei.googleapis.com/restrict.youtube.com
#cname /youtube.googleapis.com/restrict.youtube.com
#cname /www.youtube-nocookie.com/restrict.youtube.com
# Bing & DuckDuckGo Safe Mode
cname /www.bing.com/strict.bing.com
cname /duckduckgo.com/safe.duckduckgo.com
