allow-from=127.0.0.0/8
config-dir=/etc/powerdns
hint-file=/usr/share/dns/root.hints
include-dir=/etc/powerdns/recursor.d
local-address=127.0.0.1
local-port=5353
lua-config-file=/etc/powerdns/recursor.lua
max-cache-entries=1000000
max-packetcache-entries=500000
network-timeout=800
public-suffix-list-file=/usr/share/publicsuffix/public_suffix_list.dat
quiet=yes
refresh-on-ttl-perc=20
security-poll-suffix=secpoll.powerdns.com.
tcp-fast-open=1024
tcp-fast-open-connect=yes
threads=4

# Metrik untuk Prometheus
webserver=yes
webserver-address=127.0.0.1
webserver-port=8082
webserver-allow-from=127.0.0.0/8
api-key=superrahasia
